FROM grafana/grafana:10.4.1

USER root
RUN mkdir -p /etc/grafana/provisioning/datasources \
             /etc/grafana/provisioning/dashboards \
             /var/lib/grafana/dashboards

COPY infra/azure/grafana-datasource.yml  /etc/grafana/provisioning/datasources/prometheus.yml
COPY infra/azure/grafana-dashboards.yml  /etc/grafana/provisioning/dashboards/dashboards.yml
COPY infra/monitoring/dashboards/        /var/lib/grafana/dashboards/

RUN chown -R grafana:root /etc/grafana /var/lib/grafana
USER grafana

EXPOSE 3000
